version: "3.9"
services:
  frontend:
    build: nginx
    image: scmmmh/senior_common_room_nginx
    ports:
      - "0.0.0.0:8443:443"
    restart: always
    volumes:
      - ../../src/frontend/public:/usr/share/nginx/html/frontend
      - ./assets:/usr/share/nginx/html/assets
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=devPWD
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "127.0.0.1:1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
volumes:
  postgres:
